export const ADD_USER = 'ADD_USER';
export const ADD_USER_FULFILLED = 'ADD_USER_FULFILLED';
export const ADD_USER_PENDING = 'ADD_USER_PENDING';
export const ADD_USER_REJECTED = 'ADD_USER_REJECTED';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATE_USER_FULFILLED = 'AUTHENTICATE_USER_FULFILLED';
export const AUTHENTICATE_USER_PENDING = 'AUTHENTICATE_USER_PENDING';
export const AUTHENTICATE_USER_REJECTED = 'AUTHENTICATE_USER_REJECTED';

export const ADD_USER_BUDGET = 'ADD_USER_BUDGET';
export const ADD_USER_BUDGET_FULFILLED = 'ADD_USER_BUDGET_FULFILLED';
export const ADD_USER_BUDGET_PENDING = 'ADD_USER_BUDGET_PENDING';
export const ADD_USER_BUDGET_REJECTED = 'ADD_USER_BUDGET_REJECTED';

export const GET_USER_BUDGET = 'GET_USER_BUDGET';
export const GET_USER_BUDGET_FULFILLED = 'GET_USER_BUDGET_FULFILLED';
export const GET_USER_BUDGET_PENDING = 'GET_USER_BUDGET_PENDING';
export const GET_USER_BUDGET_REJECTED = 'GET_USER_BUDGET_REJECTED';

export const ADD_BUDGET_CATEGORY = 'ADD_BUDGET_CATEGORY';
export const ADD_BUDGET_CATEGORY_FULFILLED = 'ADD_BUDGET_CATEGORY_FULFILLED';
export const ADD_BUDGET_CATEGORY_PENDING = 'ADD_BUDGET_CATEGORY_PENDING';
export const ADD_BUDGET_CATEGORY_REJECTED = 'ADD_BUDGET_CATEGORY_REJECTED';

export const ADD_USER_EXPANSE = 'ADD_USER_EXPANSE';
export const ADD_USER_EXPANSE_FULFILLED = 'ADD_USER_EXPANSE_FULFILLED';
export const ADD_USER_EXPANSE_PENDING = 'ADD_USER_EXPANSE_PENDING';
export const ADD_USER_EXPANSE_REJECTED = 'ADD_USER_EXPANSE_REJECTED';

export const GET_USER_EXPANSE = 'GET_USER_EXPANSE';
export const GET_USER_EXPANSE_FULFILLED = 'GET_USER_EXPANSE_FULFILLED';
export const GET_USER_EXPANSE_PENDING = 'GET_USER_EXPANSE_PENDING';
export const GET_USER_EXPANSE_REJECTED = 'GET_USER_EXPANSE_REJECTED';


export const REMOVE_USER_EXPANSE = 'REMOVE_USER_EXPANSE';
export const REMOVE_USER_EXPANSE_FULFILLED = 'REMOVE_USER_EXPANSE_FULFILLED';
export const REMOVE_USER_EXPANSE_PENDING = 'REMOVE_USER_EXPANSE_PENDING';
export const REMOVE_USER_EXPANSE_REJECTED = 'REMOVE_USER_EXPANSE_REJECTED';

export const REMOVE_BUDGET_CATEGORY = 'REMOVE_BUDGET_CATEGORY';
export const REMOVE_BUDGET_CATEGORY_FULFILLED = 'REMOVE_BUDGET_CATEGORY_FULFILLED';
export const REMOVE_BUDGET_CATEGORY_PENDING = 'REMOVE_BUDGET_CATEGORY_PENDING';
export const REMOVE_BUDGET_CATEGORY_REJECTED = 'REMOVE_BUDGET_CATEGORY_REJECTED';

export const GET_USER_EXPANSES_AND_DATE = 'GET_USER_EXPANSES_AND_DATE';
export const GET_USER_EXPANSES_AND_DATE_FULFILLED = 'GET_USER_EXPANSES_AND_DATE_FULFILLED';
export const GET_USER_EXPANSES_AND_DATE_PENDING = 'GET_USER_EXPANSES_AND_DATE_PENDING';
export const GET_USER_EXPANSES_AND_DATE_REJECTED = 'GET_USER_EXPANSES_AND_DATE_REJECTED';

export const GET_USER_REF_TOKEN = 'GET_USER_REF_TOKEN';
export const GET_USER_REF_TOKEN_FULFILLED = 'GET_USER_REF_TOKEN_FULFILLED';
export const GET_USER_REF_TOKEN_PENDING = 'GET_USER_REF_TOKEN_PENDING';
export const GET_USER_REF_TOKEN_REJECTED = 'GET_USER_REF_TOKEN_REJECTED';
export const HANDLE_LOGOUT = 'HANDLE_LOGOUT';